### ISSUE TITLE
Use a different logo from MscrmTools' one

### ISSUE THREAD

**Issue by MscrmTools** [DigitalFlow/XrmToolBox.CloneFieldDefinitions#1]
It would be nice if you could produce your own logo for your tools!

**Comment by DigitalFlow** [comment]
Sorry, I'll create my own picture and remove yours for the time being.
Is this due to legal reasons or due to aesthetical reasons?

**Comment by MscrmTools** [comment]
Nothing legal here 😀

It's just people are identifying my plugins thanks to the picture

**Comment by DigitalFlow** [comment]
Alright, the logo is removed, I'll return with my own one 😄
