### ISSUE TITLE
Sorting not yet working on release. 

### ISSUE THREAD

**Issue by OMGUSED** [DigitalFlow/XrmToolBox.CloneFieldDefinitions#15]
For some reason, sorting is not yet working in the official repository even though the code looks ok and functioning. Can you please check?

PS. I have submitted another pull request for the descending sort in case you need to do a re-release

**Comment by DigitalFlow** [comment]
Hi @OMGUSED,

thanks for reporting.
Did you close this issue because it did work after all, or because of your PR?

Kind Regards,
Florian

**Comment by OMGUSED** [comment]
Hi Florian,

Sorry I should have placed a comment before closing. Finally it worked. I just had a backed up dll in the same directory and for some reason XrmToolBox was using that instead of the latest.

Kind Regards,
Kevin.
