### ISSUE TITLE
XrmToolbox configuration

### ISSUE THREAD

**Issue by MitchMilam** [DigitalFlow/XrmToolBox.CloneFieldDefinitions#4]
I don't see this plugin listed in the XrmToolbox plugin list. 

Why is that?

Thanks, Mitch

**Comment by DigitalFlow** [comment]
Hey @MitchMilam,

Thanks for raising this issue.
I guess the XrmToolBox dependency is outdated, thus it is not found by the plugin manager.
I'll update the reference and publish a new version of the plugin, so that it can be found and installed again.

Kind Regards,
Florian

**Comment by MitchMilam** [comment]
what would be great. I was about to point the tool to someone but couldn't find. it.

**Comment by DigitalFlow** [comment]
Hey @MitchMilam,

Everything is done, I'm only awaiting approval of MscrmTools, then the plugin will be available in the store.
I'll close this issue once approval is granted and the plugin available.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Hey @MitchMilam,

The plugin is available in the store again. 
Sorry for the delay, the approval process took quite some time. 

Kind Regards, 
Florian
