### ISSUE TITLE
Feature Request: Change Prefix

### ISSUE THREAD

**Issue by cchaney64** [DigitalFlow/XrmToolBox.CloneFieldDefinitions#5]
We have a requirement to copy fields from an existing custom entity where the publisher prefix was "new_" but we want to clone the field to a new entity with a different prefix. I believe the current prefix field on the form just adds the prefix if you're cloning an OOB field to another entity. 

Our Example:
**Source Entity:** new_installer
**Target Entity:** et_installer
**Source Field to Clone:** new_licensedate
**Target Field Name:** et_licensedate

Thanks for considering this feature!

Regards,
Chris Chaney

**Comment by DigitalFlow** [comment]
Hey @cchaney64,

Thanks for raising your request. 
I think it is completely reasonable. 
I'll add a checkbox for overriding existing publisher prefixes as soon as I have some time to spare, probably later this week. 

Kind Regards, 
Florian

**Comment by cchaney64** [comment]
Thanks @DigitalFlow !

**Comment by DigitalFlow** [comment]
Hey @cchaney64,

Your feature has been implemented.
It is available in release v1.0.36.
I'll submit the new release to XrmToolBox, but it might take a while to get it approved.
For the mean time, you can download it [here](https://ci.appveyor.com/project/DigitalFlow/xrmtoolbox-clonefielddefinitions/branch/master/artifacts), rename the .nupkg file to .zip, extract the content, copy the dll in lib to %AppData%/MscrmTools/Plugins and you're good to go.

Kind Regards,
Florian
