### ISSUE TITLE
Cannot Clone Date/Time Fields from Lead to Opportunity

### ISSUE THREAD

**Issue by zenecamickeyd** [DigitalFlow/XrmToolBox.CloneFieldDefinitions#6]
This is a great tool!  Thanks for building it!

I'm having an issue attempting to clone a number of custom fields from the Lead entity to the Opportunity entity.  When I choose _"lead"_ as the **Source Entity** all of my custom fields appear in the fields list.  When I then choose _"opportunity"_ as the **Target Entity** all of my custom Date and Time fields disappear from the fields list.  If I choose _"account"_ as the **Target Entity** all of my custom Date and Time fields remain visible.  Therefore it appears that your plugin cannot create Date and Time fields on the Opportunity entity.

Can you please help me with this?

**Comment by DigitalFlow** [comment]
Hi there,

thanks for the kind words.
I'm glad that you found the cause, that would have been my first guess as well.

Kind Regards,
Florian
