### ISSUE TITLE
Feature request: Improve visibility of entity names in source/target dropdown

### ISSUE THREAD

**Issue by gregowens** [DigitalFlow/XrmToolBox.CloneFieldDefinitions#7]
When viewing the list of options in the Source Entity and Target Entity it is not always possible to differentiate similarly named entities. For example if I have two entities:
- `new_myentitywithlongname` 
- `new_myentitywithlongnametype` 

They will both look the same in your comboboxes as they get truncated in the narrow combo box.

Possible solutions include:
- Repositioning of the combo boxes to allow them to be wider
- Tooltip on each combo box option to show the full name of the entity  

Thanks for considering the change request,.

**Comment by DigitalFlow** [comment]
Hi @gregowens,

Thanks for getting in touch. You're right, this is an issue.
I'll fix it as soon as possible.

Kind Regards,
Florian

**Comment by gregowens** [comment]
Thanks @DigitalFlow - not a show-stopper by any means though. Users can view the attributes available on each entity to help infer which entity they've selected 👍

**Comment by piyushpaliwal** [comment]
@DigitalFlow yes this is indeed a problem. Maybe just adding a tooltip would be the perfect and quick solution here.

Thanks for building this tool man, such a life-saver it is 😄
